site_name: "RBNMK"
site_description: "A blog about automating and managing your Azure infrastructure."
site_url: "https://blog.rbnmk.net"

theme:
  language: en
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        primary: black
        accent: purple

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections:
        level: 1
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - content.code.annotate
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - abbr
  - pymdownx.snippets
  - tables
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins:
  - blog:
      blog_dir: .
  - search
  - social
  - tags
  - rss:
      categories:
        - categories
        - tags
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: git
      comments_path: "#__comments"
  - git-revision-date-localized:
      timezone: Europe/Amsterdam
      fallback_to_build_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      name: Github
      link: https://github.com/rbnmk
    - icon: fontawesome/brands/linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/robinmakkus/
  analytics:
    provider: google
    property: G-MY2V1XSB91
  consent:
    title: Cookie consent
    description: >-
      I use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of my blog and whether users
      find what they're searching for. With your consent, you're helping us to
      make my page better.

copyright: >
  Copyright ©️ 2025 Robin Makkus |
  <a href="#__consent">Change cookie settings</a>
