authors:
  rbnmk:
    name: Robin Makkus # Author name
    description: "" #string # Author description
    avatar: https://media.licdn.com/dms/image/v2/D4E03AQG92Yms9YGsjg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1712569007639?e=1741219200&v=beta&t=pQci-8SXNSL9ipZhHYOGVir1VaGmPJYA5LbCbflVECs         # Author avatar
    slug: rbnmk           # Author profile slug
    url: https://rbnmk.net/about/