authors:
  rbnmk:
    name: Robin Makkus # Author name
    description: "Azure Consultant" #string # Author description
    avatar: https://blog.rbnmk.net/assets/images/bio_photo.jpg         # Author avatar
    slug: rbnmk           # Author profile slug
    url: https://www.linkedin.com/in/robinmakkus/ # Author profile URL